### ISSUE TITLE
Hi, tf.gradients vs tf.compute_gradients()

### ISSUE THREAD

**Issue by lfwin** [codekansas/tinier-nn#1]
`   
 for p, prev_layer, w, bin_w in updates[::-1]:

        w_grad, loss_grad = tf.gradients(p, [bin_w, prev_layer], loss_grad)

        backprop_updates.append((w_grad, w))
`
Does tf.gradients have the same effect of using optimizer.compute_gradients(loss, var_list)?

**Comment by codekansas** [comment]
Not exactly, and it wouldn't work for this application (although the official implementation has a better version of the binarization step which would let it work). The `loss_grad` part carries over the gradient between layers (skipping the binarization part). But otherwise they're the same.
